-- MySQL Script generated by MySQL Workbench
-- 02/07/17 09:51:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sw_control
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sw_control` ;

-- -----------------------------------------------------
-- Schema sw_control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sw_control` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `sw_control` ;

-- -----------------------------------------------------
-- Table `laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratorio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `laboratorio` (
  `ID_LABORATORIO` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `NOMBRE_LAB` CHAR(10) NOT NULL,
  `NUM_AULA` SMALLINT(6) NOT NULL,
  `CAPACIDAD` SMALLINT(6) NOT NULL,
  `DESC_UBICACION` VARCHAR(100) NULL DEFAULT NULL,
  `NUM_ORDENADORES` SMALLINT(6) NOT NULL,
  `PROY_EMPOTRADO` CHAR(2) NOT NULL DEFAULT 'NO',
  PRIMARY KEY (`ID_LABORATORIO`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_LABORATORIO_UNIQUE` ON `laboratorio` (`ID_LABORATORIO` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `laboratorio_materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratorio_materia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `laboratorio_materia` (
  `ID_LABORATORIO` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`ID_LABORATORIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `programa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `programa` (
  `ID_PROGRAMA` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `NOMBRE_PROG` CHAR(30) NOT NULL,
  `TIPO` CHAR(20) NULL DEFAULT 'SIN ASIGNAR',
  `SERVICIO` CHAR(15) NULL DEFAULT 'S/A',
  `CATEGORIA` CHAR(10) NOT NULL,
  `VERSION` CHAR(10) NULL DEFAULT NULL,
  `ANIO` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PROGRAMA`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_PROGRAMA_UNIQUE` ON `programa` (`ID_PROGRAMA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `laboratorio_programa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `laboratorio_programa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `laboratorio_programa` (
  `ID_LABORATORIO` SMALLINT(6) NOT NULL,
  `ID_PROGRAMA` SMALLINT(6) NOT NULL,
  PRIMARY KEY (`ID_LABORATORIO`, `ID_PROGRAMA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `materia` (
  `ID_MATERIA` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `CODIGO_MAT` CHAR(6) NOT NULL,
  `NOMBRE_MAT` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID_MATERIA`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ID_MATERIA_UNIQUE` ON `materia` (`ID_MATERIA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `materia_prog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia_prog` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `materia_prog` (
  `ID_PROGRAMA` SMALLINT(6) NOT NULL,
  `ID_MATERIA` SMALLINT(6) NOT NULL,
  `ESTADO` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID_PROGRAMA`, `ID_MATERIA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `profesor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `profesor` (
  `idprofesor` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `nombre_apellido_prof` VARCHAR(100) NOT NULL,
  `correo_prof` VARCHAR(60) NOT NULL,
  `num_intentos` SMALLINT(4) NULL DEFAULT 0,
  PRIMARY KEY (`idprofesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idprofesor_UNIQUE` ON `profesor` (`idprofesor` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `materia_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia_grupo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `materia_grupo` (
  `idMateria_grupo` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `grupo_Materia` VARCHAR(6) NOT NULL,
  `materia` SMALLINT(6) NULL DEFAULT NULL,
  `profesor` SMALLINT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`idMateria_grupo`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idMateria_grupo_UNIQUE` ON `materia_grupo` (`idMateria_grupo` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
